### ISSUE TITLE
Android Pre-launch check: Unsupported APIs

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#1003]
Received the following errors from the Play Store Pre-launch check (for app v0.6.1, version code 12):

Unsupported
 4 warnings identified
The following APIs are greylisted and Google can’t guarantee that they will work on existing versions of Android. Some may be already be restricted for your target SDK

## API Landroid/util/LongArray;->get(I)J
2 occurrences identified. Only unique stack traces are shown.

Stack trace 1

```StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/util/LongArray;->get(I)J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:113)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:153)
	at c.a.b.a.l.a(Unknown Source:152)
	at c.a.b.a.e$b.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Stack trace 2

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/util/LongArray;->get(I)J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:113)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:153)
	at c.a.b.a.l.a(Unknown Source:152)
	at c.a.b.a.e$b.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

## API Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J
2 occurrences identified. Only unique stack traces are shown.

Stack trace 1

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:13)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:153)
	at c.a.b.a.l.a(Unknown Source:152)
	at c.a.b.a.e$b.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Stack trace 2

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:13)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:153)
	at c.a.b.a.l.a(Unknown Source:152)
	at c.a.b.a.e$b.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

## API Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray;
2 occurrences identified. Only unique stack traces are shown.

Stack trace 1

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:92)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:153)
	at c.a.b.a.l.a(Unknown Source:152)
	at c.a.b.a.e$b.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Stack trace 2

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:92)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:153)
	at c.a.b.a.l.a(Unknown Source:152)
	at c.a.b.a.e$b.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

## API Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J
2 occurrences identified. Only unique stack traces are shown.

Stack trace 1

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:28)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:153)
	at c.a.b.a.l.a(Unknown Source:152)
	at c.a.b.a.e$b.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Stack trace 2

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:28)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:153)
	at c.a.b.a.l.a(Unknown Source:152)
	at c.a.b.a.e$b.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by hspinks** [comment]
Possibly fixed in #937 which was not in the last build...

**Comment by epicfaace** [comment]
These 4 issues are a known problem with flutter -- see https://github.com/flutter/flutter/issues/36915#issuecomment-525668810

@richgoldmd writes:

> So the play store will issue warnings because a deprecated API is indeed called from the source, however, it is called in a way that is compatible with future versions where those APIs are no longer available. As a result, I regard the warnings as a non-issue, as long as I (or the flutter devs) don't add additional, non-protected calls to these APIs - these warnings are expected. I think they should be documented however, so that flutter developers know to expect them.

So we should be okay.

**Comment by epicfaace** [comment]
@advayDev1 there's a comment in the above issue in the Flutter source code saying, "If the reflection accessors are not available we fail silently by embedding a null node, the app continues working but the accessibility information for the platform view will not be embedded."

I'd be inclined to trust the Flutter devs on this and treat this as a non-issue.

**Comment by epicfaace** [comment]
Assigning this to @pwicherski -- all that's left here is to test this app on the oldest android API that we support, just to make sure that nothing crashes on it.

**Comment by pwicherski** [comment]
Checked on Nexus S Android 4.1.2 (API level 16) and looks like it's working 👍 
I'm trying to buy some API 16 devices, but it will take some time.

I'm closing this issue and I will keep an eye on it 👀
